"""Initial migration.

Revision ID: 9e7f7c3bdf66
Revises:
Create Date: 2022-10-03 21:21:40.495562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e7f7c3bdf66'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jogo_favorito',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('steam_id_jogo', sa.String(length=50), nullable=False),
    sa.Column('url_capa', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jogo_favorito_usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('jogo_favorito_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['jogo_favorito_id'], ['jogo_favorito.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jogo_favorito_usuario')
    op.drop_table('jogo_favorito')
    # ### end Alembic commands ###
