"""aumentando a string da url_capa para 200

Revision ID: f27a8ffb343c
Revises: e5a28dcac177
Create Date: 2022-10-04 16:48:58.722283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f27a8ffb343c'
down_revision = 'e5a28dcac177'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jogo_favorito', sa.Column('url_capa', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jogo_favorito', 'url_capa')
    # ### end Alembic commands ###
