name: Pull Request

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Configurar Python 3.10.4
      uses: actions/setup-python@v3
      with:
        python-version: 3.10.4
    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install -r requirements-test.txt
    - name: Analisando código com Pylint
      run: pylint $(git ls-files '*.py')
    - name: Executando testes unitários
      run: pytest
